### ISSUE TITLE
Light on edges of blocks while underground

### ISSUE THREAD

**Issue by ChildishGiant** [rre36/glsl_vplus#3]
![image](https://user-images.githubusercontent.com/13716824/65379959-eda38f80-dcc8-11e9-8264-3c6234d05192.png)

There's a seam of light around these block but I'm in a mine and went into spectator mode and there are no caves around

**Comment by rre36** [comment]
This caused by the chunks above not being loaded. Unfortunately this is nothing a shader can influence and thus is to blame on Minecrafts chunkloading. It's a very well known bug across the shader community.
